sequenceDiagram
    participant browser
    participant server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server-->>browser: {content: "HI", date: "2024-08-15T15:23:41.824Z"}
    deactivate server
